# Generated by cpp4r: do not edit by hand

#' @title Main VAR estimation function that returns everything
#' @export
var_model <- function(y, p, include_const, forecast_h) {
	.Call(`_ecod025ps1_var_model`, y, p, include_const, forecast_h)
}

#' @title Main FAVAR estimation function
#' @export
favar_model <- function(y, x, n_factors, p_y, p_f, include_const, forecast_h) {
	.Call(`_ecod025ps1_favar_model`, y, x, n_factors, p_y, p_f, include_const, forecast_h)
}

#' @title Main DFM estimation function
#' @export
dfm_model <- function(x, n_factors, p, include_const, max_iter, tol, forecast_h, n_lags) {
	.Call(`_ecod025ps1_dfm_model`, x, n_factors, p, include_const, max_iter, tol, forecast_h, n_lags)
}

#' @title Predictive DFM
#' @description Uses factors from covariates X to predict target variable y. This is similar to FA-VAR but uses DFM factor
#'   extraction
#' @export
dfm_predict_model <- function(y, x, n_factors, p_y, p_f, include_const, max_iter, tol, forecast_h) {
	.Call(`_ecod025ps1_dfm_predict_model`, y, x, n_factors, p_y, p_f, include_const, max_iter, tol, forecast_h)
}
