# Generated by cpp4r: do not edit by hand

#' @title Main VAR estimation function that returns everything
#' @description Estimates a VAR model using OLS.
#' @param y Time series vector (T x 1)
#' @param p Lag order
#' @param include_const Include constant term in VAR
#' @param forecast_h Forecast horizon (0 for no forecast)
#' @export
var_model <- function(y, p, include_const, forecast_h) {
	.Call(`_ecod025ps1_var_model`, y, p, include_const, forecast_h)
}

#' @title Factor-Augmented VAR (FA-VAR) Model
#' @description Estimates a FA-VAR model using PCA for factor extraction.
#' @param y Time series vector (T x 1)
#' @param n_lags Number of lags of y to include in X for factor extraction
#' @param n_factors Number of latent factors to extract (r < n_lags + 1)
#' @param p_y VAR lag order for y dynamics
#' @param p_f VAR lag order for factor dynamics
#' @param include_const Include constant term in VARs
#' @param forecast_h Forecast horizon (0 for no forecast)
#' @export
favar_model <- function(y, n_lags, n_factors, p_y, p_f, include_const, forecast_h) {
	.Call(`_ecod025ps1_favar_model`, y, n_lags, n_factors, p_y, p_f, include_const, forecast_h)
}

#' @title Dynamic Factor Model (DFM)
#' @description Estimates a Dynamic Factor Model using PCA initialization and EM algorithm with Kalman filter.
#' @param x Matrix of observed variables (T x N)
#' @param n_factors Number of latent factors (r < N)
#' @param p VAR lag order for factor dynamics (0 for static model)
#' @param max_iter Maximum EM iterations
#' @param tol Convergence tolerance for log-likelihood
#' @param forecast_h Forecast horizon (0 for no forecast)
#' @export
dfm_model <- function(x, n_factors, p, max_iter, tol, forecast_h) {
	.Call(`_ecod025ps1_dfm_model`, x, n_factors, p, max_iter, tol, forecast_h)
}
